import {
    BADGE_PIONEER_KEY,
    BADGE_XP_LEVEL_KEY,
    BADGE_DELEGATE_KEY,
    BADGE_SECOND_PASSPHRASE_KEY,
} from "../../../../types";
import { LIFE_CYCLE_PROPERTY_KEY } from "@uns/crypto";

export const ACTIVE_BADGES = [BADGE_DELEGATE_KEY, BADGE_SECOND_PASSPHRASE_KEY, BADGE_PIONEER_KEY, BADGE_XP_LEVEL_KEY];
export const ACTIVE_SYSTEM_PROPERTIES = ["type", "explicitValues", LIFE_CYCLE_PROPERTY_KEY];
