import { LIFE_CYCLE_PROPERTY_KEY } from "@uns/crypto";
import {
    AUTHENTICATIONS_COSMIC_NONCE,
    BADGE_DELEGATE_KEY_REGEXP,
    BADGE_EVENTS_PREFIX_REGEXP,
    BADGE_XP_LEVEL_KEY_REGEXP,
    BADGE_PIONEER_KEY_REGEXP,
    BADGE_SECOND_PASSPHRASE_KEY_REGEXP,
} from "../../../functions/unik/constants";

export const ACTIVE_BADGES_REGEXP: RegExp[] = [
    BADGE_DELEGATE_KEY_REGEXP,
    BADGE_SECOND_PASSPHRASE_KEY_REGEXP,
    BADGE_PIONEER_KEY_REGEXP,
    BADGE_XP_LEVEL_KEY_REGEXP,
    BADGE_EVENTS_PREFIX_REGEXP,
];
export const ACTIVE_SYSTEM_PROPERTIES = [
    "type",
    "explicitValues",
    LIFE_CYCLE_PROPERTY_KEY,
    AUTHENTICATIONS_COSMIC_NONCE,
];
export { LIFE_CYCLE_PROPERTY_KEY } from "@uns/crypto";
